### ISSUE TITLE
Type hinting versioning issue

### ISSUE THREAD

**Issue by jasonwu224** [stfnw/fuse-monitor-read-write#1]
Hi, I found a versioning issue where the type hint

```
def map_chunks(rng: Range, sidelength_px: int, filesize: int) -> Generator[Pixel]:
```

Works in python version 3.13 but not 3.9, 3.11, or 3.12. If I try to run your program in any of the latter versions, I get this error:

```
Traceback (most recent call last):
  File "/root/test.py", line 8, in <module>
    def my_generator() -> Generator[Pixel]:
                          ~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.11/typing.py", line 379, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/typing.py", line 1592, in __getitem__
    _check_generic(self, params, self._nparams)
  File "/usr/lib64/python3.11/typing.py", line 293, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too few arguments for typing.Generator; actual 1, expected 3
```

**Comment by stfnw** [comment]
Thanks; just fixed it.
